SELECT AUTHOR_ID, (SELECT AUTHOR_NAME
                  FROM AUTHOR
                  WHERE AUTHOR_ID = B.AUTHOR_ID) AS AUTHOR_NAME, 
    CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK_SALES S
JOIN BOOK B
ON S.BOOK_ID = B.BOOK_ID
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC