SELECT A.ID
FROM ECOLI_DATA A
JOIN ECOLI_DATA B
ON A.PARENT_ID = B.ID
WHERE B.PARENT_ID IS NOT NULL AND 
    (SELECT C.PARENT_ID
     FROM ECOLI_DATA C
     WHERE ID = B.PARENT_ID) IS NULL
ORDER BY A.ID