WITH NO_DAEYEO AS (SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'),
DISCOUNT AS (SELECT CAR_TYPE, DISCOUNT_RATE
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
            WHERE DURATION_TYPE = '30일 이상')
SELECT CAR_ID, CAR_TYPE, ROUND((DAILY_FEE * 30 * (1-IFNULL((
    SELECT DISCOUNT_RATE
    FROM DISCOUNT
    WHERE CAR_TYPE = C.CAR_TYPE),0)
                          / 100)),0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
WHERE (CAR_TYPE = '세단' OR CAR_TYPE = 'SUV') AND 
    CAR_ID NOT IN (SELECT * FROM NO_DAEYEO)
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC