SELECT COUNT(*) AS FISH_COUNT, 
    (SELECT FISH_NAME 
     FROM FISH_NAME_INFO 
     WHERE FNI.FISH_TYPE = FISH_TYPE) AS FISH_NAME
FROM FISH_INFO FI
INNER JOIN FISH_NAME_INFO FNI
ON FI.FISH_TYPE = FNI.FISH_TYPE
GROUP BY FNI.FISH_TYPE
ORDER BY FISH_COUNT DESC
;