WITH MAKE_GRADE AS (
    SELECT EMP_NO, CASE
    WHEN AVG(SCORE) >= 96 THEN 'S'
    WHEN AVG(SCORE) >= 90 THEN 'A'
    WHEN AVG(SCORE) >= 80 THEN 'B'
    ELSE 'C'
    END AS MAKE_GRADE
    FROM HR_GRADE
    GROUP BY EMP_NO
)
SELECT E.EMP_NO, EMP_NAME, MAKE_GRADE AS GRADE,
   CASE 
   WHEN MAKE_GRADE = 'S' THEN SAL * 0.2
   WHEN MAKE_GRADE = 'A' THEN SAL * 0.15
   WHEN MAKE_GRADE = 'B' THEN SAL * 0.1
   ELSE 0
   END AS BONUS
FROM HR_EMPLOYEES E
JOIN MAKE_GRADE M
ON E.EMP_NO = M.EMP_NO
ORDER BY E.EMP_NO