SELECT
INFO.ITEM_ID, ITEM_NAME, RARITY
FROM
ITEM_INFO INFO
INNER JOIN ITEM_TREE TREE
ON INFO.ITEM_ID = TREE.ITEM_ID
WHERE TREE.PARENT_ITEM_ID IN (SELECT ITEM_ID 
                              FROM ITEM_INFO 
                              WHERE RARITY = 'RARE') 
ORDER BY
INFO.ITEM_ID DESC
;