SELECT DISTINCT HT.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HT
INNER JOIN CAR_RENTAL_COMPANY_CAR CAR
ON HT.CAR_ID = CAR.CAR_ID
WHERE CAR_TYPE = '세단' AND MONTH(START_DATE) = 10
ORDER BY HT.CAR_ID DESC