SELECT (SELECT SUM(SCORE) 
        FROM HR_GRADE HG
        WHERE YEAR = 2022 AND HE.EMP_NO = HG.EMP_NO) AS SCORE, 
        EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES HE
ORDER BY SCORE DESC
LIMIT 1
;

