SELECT DEPT_ID, 
    (SELECT DEPT_NAME_EN
    FROM HR_DEPARTMENT
    WHERE HE.DEPT_ID = DEPT_ID) AS DEPT_NAME_EN,
    ROUND(AVG(SAL)) AS AVG_SAL
FROM HR_EMPLOYEES HE
GROUP BY DEPT_ID
ORDER BY AVG_SAL DESC